name: Catroid Pipeline

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
  #  schedule:
  #    - cron: "0 0 * * *" # Run daily at midnight
  workflow_dispatch:
    inputs:
      WEB_TEST_URL:
        description: "When set, all the archived APKs will point to this Catrobat web server, useful for testing web changes. E.g https://web-test.catrob.at"
        required: false
        type: string
        default: ""
      BUILD_ALL_FLAVOURS:
        description: "When selected all flavours are built and archived as artifacts that can be installed alongside other versions of the same APKs"
        required: false
        type: boolean
        default: false

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    env:
      WEB_TEST_URL: ${{ inputs.WEB_TEST_URL != '' && format('-PwebTestUrl=''{0}''', inputs.WEB_TEST_URL) || '' }}
      ALL_FLAVOURS_PARAMETERS: ${{ inputs.BUILD_ALL_FLAVOURS && 'assembleCreateAtSchoolDebug assembleLunaAndCatDebug assemblePhiroDebug assembleEmbroideryDesignerDebug assemblePocketCodeBetaDebug assembleMindstormsDebug' || '' }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build APK
        run: ./gradlew ${{ env.WEB_TEST_URL }} -Pindependent='#${{ github.run_number }} ${{ github.ref_name }}' assembleCatroidDebug ${{ env.ALL_FLAVOURS_PARAMETERS }}
  # TODO: Check where to upload the APKs as GitHub Storage is an issue
  #
  #      - name: Rename APKs
  #        run: |
  #          for file in $(find . -name "*.apk"); do
  #            mv "$file" "$(dirname "$file")/${{ github.ref_name }}-${{ github.run_number }}-$(basename "$file")"
  #          done
  #
  #      - name: Archive APKs
  #        uses: actions/upload-artifact@v4
  #        with:
  #          name: apk-artifacts
  #          path: "**/*.apk"

  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    env:
      WEB_TEST_URL: ${{ inputs.WEB_TEST_URL != '' && format('-PwebTestUrl=''{0}''', inputs.WEB_TEST_URL) || '' }}
      ALL_FLAVOURS_PARAMETERS: ${{ inputs.BUILD_ALL_FLAVOURS && 'assembleCreateAtSchoolDebug assembleLunaAndCatDebug assemblePhiroDebug assembleEmbroideryDesignerDebug assemblePocketCodeBetaDebug assembleMindstormsDebug' || '' }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Unit Tests
        run: ./gradlew -PenableCoverage jacocoTestCatroidDebugUnitTestReport --full-stacktrace
        continue-on-error: true

      - name: Upload Unit Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-reports
          path: |
            catroid/build/reports/jacoco/jacocoTestCatroidDebugUnitTestReport.xml
            catroid/build/reports/tests/testDebugUnitTest

  code-analysis:
    name: Code analysis
    runs-on: ubuntu-latest
    env:
      WEB_TEST_URL: ${{ inputs.WEB_TEST_URL != '' && format('-PwebTestUrl=''{0}''', inputs.WEB_TEST_URL) || '' }}
      ALL_FLAVOURS_PARAMETERS: ${{ inputs.BUILD_ALL_FLAVOURS && 'assembleCreateAtSchoolDebug assembleLunaAndCatDebug assemblePhiroDebug assembleEmbroideryDesignerDebug assemblePocketCodeBetaDebug assembleMindstormsDebug' || '' }}
    permissions:
      security-events: write
      packages: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      #######################################################################################
      - name: PMD
        run: ./gradlew pmd

      - name: Upload Static Analysis Reports
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: pmd-report
          path: |
            catroid/build/reports/pmd.html
      #######################################################################################
      - name: Checkstyle
        run: ./gradlew checkstyle

      - name: Upload Checkstyle Report
        uses: github/codeql-action/upload-sarif@v3
        if: success() || failure()
        with:
          sarif_file: catroid/build/reports/checkstyle.sarif
          category: "Checkstyle"
      #######################################################################################
      - name: Detekt
        run: ./gradlew detekt

      - name: Upload Detekt Report as HTML
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: detekt-report
          path: |
            catroid/build/reports/detekt.html

      - name: Upload Detekt Report
        uses: github/codeql-action/upload-sarif@v3
        if: success() || failure()
        with:
          sarif_file: catroid/build/reports/detekt.sarif
          category: "Detekt"
      #######################################################################################
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: java-kotlin
          build-mode: manual

      - name: Dev Build
        run: ./gradlew assembleCatroidDebug

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:$java-kotlin"
      #######################################################################################
      - name: Lint
        run: ./gradlew lintCatroidDebug

      - name: Upload Lint Report
        uses: github/codeql-action/upload-sarif@v3
        if: success() || failure()
        with:
          sarif_file: catroid/build/reports/lint/lintCatroidDebug.xml
          category: "Lint"
#######################################################################################
