name: Catroid CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
  #  schedule:
  #    - cron: "0 0 * * *" # Run daily at midnight
  workflow_dispatch:
    inputs:
      WEB_TEST_URL:
        description: "When set, all the archived APKs will point to this Catrobat web server, useful for testing web changes. E.g https://web-test.catrob.at"
        required: false
        type: string
        default: ""
      ANDROID_VERSION:
        description: "The Android version to use for the build"
        required: false
        type: string
        default: "34"
      BUILD_ALL_FLAVOURS:
        description: "When selected all flavours are built and archived as artifacts that can be installed alongside other versions of the same APKs"
        required: false
        type: boolean
        default: false
      DISABLE_UNIT_TESTS:
        description: "Disables Unit Tests"
        required: false
        type: boolean
        default: false

jobs:
  instrumentation-tests:
    name: Instrumentation tests
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        api-level: [34]

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 21

      - uses: gradle/actions/setup-gradle@v4

      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Instrumentation tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          target: aosp_atd
          profile: Nexus One
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: |
            adb shell wm density 240
            ./gradlew connectedCatroidDebugAndroidTest --stacktrace
